version: "3"
volumes:
  web_root:
services:
  ui:
    build:
      context: ui
    volumes:
      - ./ui/app:/app
      - "web_root:/app/dist:z"
    hostname: ui
    restart: "no"
    env_file: .env
  fuseki:
    image: secoresearch/fuseki
    ports:
      - "3030:3030"
    hostname: fuseki
    environment:
      - ADMIN_PASSWORD=admin
      - ENABLE_DATA_WRITE=true
      - ENABLE_UPDATE=true
      - ENABLE_UPLOAD=true
      - QUERY_TIMEOUT=3000
    volumes:
      - ./data:/fuseki-base/databases
  anzo:
    image: cambridgesemantics/anzograph
    ports:
      - 8080:8080
      - 8443:8443
    hostname: anzo
    volumes:
      - ./shared-files:/opt/shared-files
