version: "3"
volumes:
  web_root:
  anzo_data:
  rdfox_data:
  graphdb_data:
services:
  ui:
    build:
      context: ui
    volumes:
      - ./ui/app:/app
      - "web_root:/app/dist:z"
    hostname: ui
    restart: "no"
    env_file: .env
  fuseki:
    image: secoresearch/fuseki
    ports:
      - "3030:3030"
    hostname: fuseki
    environment:
      - ADMIN_PASSWORD=admin
      - ENABLE_DATA_WRITE=true
      - ENABLE_UPDATE=true
      - ENABLE_UPLOAD=true
      - QUERY_TIMEOUT=3000
    volumes:
      - ./data:/fuseki-base/databases
  anzo:
    image: cambridgesemantics/anzograph
    ports:
      - 8080:8080
      - 8443:8443
    hostname: anzo
    volumes:
      - ./shared-files:/opt/shared-files
      - "./anzo/config:/opt/anzograph/config"
      - "anzo_data:/opt/anzograph/persistence"
  graphdb:
    build:
      context: graphdb
    ports:
      - 7200:7200
    hostname: graphdb
    volumes:
      - ./shared-files:/opt/shared-files
      - "graphdb_data:/opt/graphdb/home"
    environment:
      - GDB_JAVA_OPTS=-Dgraphdb.home=/opt/graphdb/home
  rdfox:
    image: oxfordsemantic/rdfox:6.3a
    ports:
      - 12110:12110
    volumes:
      - ./rdfox/RDFox.lic:/opt/RDFox/RDFox.lic:ro
      - rdfox_data:/home/rdfox/.RDFox
    cap_drop:
      - ALL
